### ISSUE TITLE
Isur melacha sensor

### ISSUE THREAD

**Issue by aviadlevy** [rt400/Jewish-Sabbaths-Holidays#12]
I understand and love the separation you made between shabbat and yomtov, and it's indeed helpful. 
Still, I sometime do find myself adding "and" condition that checking if it's not shabbat and not yomtov. 
Do you think there is a place to another sensor represent this condition (isur melacha or whatever other name you'll decide to call it)

If so, I would love to try and open a PR for this change and contribute

Thanks

**Comment by rt400** [comment]
cant make sensor for shabbat and yomtov together cause in there is no data for yomtov (data like the datetime variable) and cant run with it in the function.
