### ISSUE TITLE
Jerusalmem candle light

### ISSUE THREAD

**Issue by lidans5** [rt400/Jewish-Sabbaths-Holidays#13]
When adding:
jerusalem_candle: True to the yaml configuration file
the integration stops working

**Comment by rt400** [comment]
change the True to true and check it plz

**Comment by lidans5** [comment]
didn't help
when adding jerusalem... all entities are gone

**Comment by rt400** [comment]
plz share your config in code mode

**Comment by rt400** [comment]
the sensor config

**Comment by rt400** [comment]
I think that you may not have the last update... 
I see that I already fix that typo

**Comment by lidans5** [comment]
I can't see any difference between your config and my
and when verifying configuration, getting this message:
Invalid config for [sensor.hebcal]: [jerualem_candle] is an invalid option for [sensor.hebcal]. Check: sensor.hebcal->jerualem_candle. (See ?, line ?).

**Comment by rt400** [comment]
you got this error cause you in the version before the typo fix. try to use this `jerusalem_candel: True` and see if its work

**Comment by lidans5** [comment]
> 
" its should be jerusalem_candle but its jerusalem_candel"
**It should be jerusalem_candel** - you meant 
indeed jerusalem candel works - Thanks!!!

**Comment by rt400** [comment]
you should update to the last version cause i the last version is `jerusalem_candle: True`

**Comment by lidans5** [comment]
no update available in my Hacs...

**Comment by rt400** [comment]
which version you have?

**Comment by lidans5** [comment]
2.0.8

**Comment by rt400** [comment]
i make new version plz check it and fix the typo
