### ISSUE TITLE
Error in counting the Omer

### ISSUE THREAD

**Issue by meni123** [rt400/Jewish-Sabbaths-Holidays#14]
It worked great for me until today, I started receiving a message during the Omer count that there is no Omer count, what could be the problem?

**Comment by rt400** [comment]
check the logs, see if you have any error message about it.
also share your config to

**Comment by meni123** [comment]
I have no errors so it is set for me,

`- platform: hebcal
  havdalah_calc: 42
  time_before_check: 10
  time_after_check: 1
  tzeit_hakochavim: False
  omer_count_type: 1
  resources:
      - shabbat_in
      - shabbat_out
      - parasha
      - hebrew_date
      - is_shabbat
      - yomtov_in
      - yomtov_out
      - is_yomtov
      - yomtov_name
      - event_name
      - omer_day
      - zmanim`

This problem is solved, but I have a new problem,
The date is Monday and the time is 18:00. You can see that the city is set for me and the sun has not yet set, but it shows the count for tomorrow,
He writes to me that it will be in an hour,
what can be done?
Thank you

**Comment by meni123** [comment]
my problem is solved
I had a problem with the system clock,
Thank you for the wonderful plugins!
