### ISSUE TITLE
Warning in log

### ISSUE THREAD

**Issue by felix63** [rt400/Jewish-Sabbaths-Holidays#15]
Since latest version logs show warnings regarding your excellent integration

`
Logger: homeassistant.helpers.entity
Source: helpers/entity.py:554 
First occurred: 00:40:43 (6 occurrences) 
Last logged: 00:40:43

Entity sensor.hebcal_is_shabbat (<class 'custom_components.hebcal.sensor.Hebcal'>) is using self.async_update_ha_state(), without enabling force_update. Instead it should use self.async_write_ha_state(), please report it to the custom integration author.
Entity sensor.hebcal_parasha (<class 'custom_components.hebcal.sensor.Hebcal'>) is using self.async_update_ha_state(), without enabling force_update. Instead it should use self.async_write_ha_state(), please report it to the custom integration author.
Entity sensor.hebcal_shabbat_entry (<class 'custom_components.hebcal.sensor.Hebcal'>) is using self.async_update_ha_state(), without enabling force_update. Instead it should use self.async_write_ha_state(), please report it to the custom integration author.
Entity sensor.hebcal_event_name (<class 'custom_components.hebcal.sensor.Hebcal'>) is using self.async_update_ha_state(), without enabling force_update. Instead it should use self.async_write_ha_state(), please report it to the custom integration author.
Entity sensor.hebcal_shabbat_came_out (<class 'custom_components.hebcal.sensor.Hebcal'>) is using self.async_update_ha_state(), without enabling force_update. Instead it should use self.async_write_ha_state(), please report it to the custom integration author.
`

**Comment by rt400** [comment]
It was fixed in this release
