### ISSUE TITLE
Typo in suggested config file on homepage

### ISSUE THREAD

**Issue by danielrosehilljlm** [rt400/Jewish-Sabbaths-Holidays#17]
Hey - just FYI as people (like me!) might copy and paste the default config file on the homepage into their configuration.yaml and if they do they'll end up without the add-on because jerusalem_candle chokes it (you have jerualem_candle rather than jerusalem_candle):

![typo](https://github.com/rt400/Jewish-Sabbaths-Holidays/assets/40233203/a353be5e-ac0a-4680-ac47-70bf4950c88d)

Many thanks for making this!

**Comment by rt400** [comment]
Fix it. Thanks...
