### ISSUE TITLE
sensor.hebcal_is_yomtov returns "No Info"

### ISSUE THREAD

**Issue by danielrosehill** [rt400/Jewish-Sabbaths-Holidays#18]
Current sensor condition for "is_yomtov" returns "No info".

Is the integration broken? (I assume it's supposed to be the same True/False flag as is_shabbat).

If not perhaps it could be changed to True/False for ease of use and configuring automations.

![no info yom tov](https://github.com/rt400/Jewish-Sabbaths-Holidays/assets/40233203/64328ee5-1547-4b9b-8080-51a480287373)

**Comment by rt400** [comment]
Hi,
When you see "No Info" its means that there is no data... cause no yomtov in this week.
Also you can set Hebrew is the integration and you will get "אין מידע". 
when HA goes up then the sensor "is_yomtov" is in "unknown" status and as soon as the integration updates the sensor information it becomes FALSE. So if you have an automation based on this TRUE/FALSE you might trigger it.

**Comment by danielrosehilljlm** [comment]
@rt400 - Thanks for the info - and for developing this!

I wrote up a little blog last night about a little project I made using it (just a little light to indicate when Shabbat is in). This Shabbat, it will be powering a bunch of automations.

https://www.hackster.io/danielrosehill/a-simple-shabbat-indicator-light-using-home-assistant-842571

**Comment by danielrosehilljlm** [comment]
> Thanks.. You have to mistake :
> 
> 1. Fix jerusalem typo in code.
> 2. My Name is Yuval Mejahez not Yuval Abolafia... (I am the writer of this integration ...)
>    ![image](https://private-user-images.githubusercontent.com/38878996/314094500-29c9d984-7a70-436b-877d-81da893a4b38.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4NTk2NzksIm5iZiI6MTcxMDg1OTM3OSwicGF0aCI6Ii8zODg3ODk5Ni8zMTQwOTQ1MDAtMjljOWQ5ODQtN2E3MC00MzZiLTg3N2QtODFkYTg5M2E0YjM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE5VDE0NDI1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyYTExMmQwMDM1ZmNhMjkyYWY1N2MzZTZkOGZhNDhkZGRkZWEyYTcwZTBhNGVhODYyYmFjZWEyNTlmMDQxZjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aTmlYy0XPDN1pR2-DliLRO72MRIWIrZvGv6Nxtqb3fk)

Will update!

**Comment by danielrosehilljlm** [comment]
> You have to mistake :
> 
> 1. Fix jerusalem typo in code.
> 2. My Name is Yuval Mejahez not Yuval Abolafia... (I am the writer of this integration ...)

Both updated
