### ISSUE TITLE
One request for help (30 minutes until Shabbat time)

### ISSUE THREAD

**Issue by danielrosehill** [rt400/Jewish-Sabbaths-Holidays#20]
Hey!

Hope it's okay to drop in here with a quick request for help if anyone can offer it.

I'd like to create a notification for when it's 30 minutes until Shabbat.

I'm guessing that the logical sensor to poll for the timestamp is:

`sensor.jewish_calendar_upcoming_candle_lighting`

Has anyone figured out a clever way to trigger an automation based on an amount of time preceding that (like in my case 30 minutes)?

TIA

**Comment by rt400** [comment]
Sorry its looks that you used the other shabbat times. 
In my integration you can set in yaml sensor configuration instead 10 min before a 30 min before with out change it with automation.
