### ISSUE TITLE
Will it work with no Internet 

### ISSUE THREAD

**Issue by mordhollander** [rt400/Jewish-Sabbaths-Holidays#22]
Hi 
Would this integration work well when the Internet is down 
Or does it need a live internet connection for the automations to run 

As I have home assistant installed and running where there is no Internet connection 
I an have Internet when installing or programming the automations but once it's set up and running there will be no Internet connection 

Thank you

**Comment by rt400** [comment]
No. you must have internet connection to make this integration work well.
