### ISSUE TITLE
Rosh Hashana Day 2 and « is yomtov »

### ISSUE THREAD

**Issue by Mimaf3** [rt400/Jewish-Sabbaths-Holidays#23]
Hello, 

First thank you for this awesome sensor !

Tonight is Rosh Hashana day 2, but the « is yomtov » sensor came back to « False » (and my test automations stopped because depending on the status « true » of the sensor )

why is that ?  Knowing that even in Israël Rosh Hashana last 2 days ?

and other question : the « is yomtov » sensor used to be on « no info » when off, but is now on false, is it new and Will it always be like this ? So I can change my automation ?

thank you

**Comment by rt400** [comment]
@Mimaf3 you need to update the integration to the latest version...
@bru73f0rc3 its work for you because you have the latest version.
there is was a bug that make RoshHashana 1 day instead 2 days. i was  fix it in the last sunday (29/09/2024)
