### ISSUE TITLE
diffrenet holidays automation

### ISSUE THREAD

**Issue by zeev-mindali** [rt400/Jewish-Sabbaths-Holidays#25]
how can i make an automation depends on specific holyday?

i have diffrent time for yum kipor , sukkot and pass over.

zeev

**Comment by rt400** [comment]
what did you mean differents times?
the automation you can make is base on is_yom_tov or is_shabbat only

**Comment by zeev-mindali** [comment]
@rt400 

i want diffrent times for diffrenet holidays
yum kippur has for me diffrent time from sukot.

**Comment by rt400** [comment]
the holiday time has changed once a week (on Sunday at 00:00 AM).
so the times you have is only for present week and go on...

**Comment by zeev-mindali** [comment]
understood, but if i want diffrent automation for diffrent holidaies?
i search for name, but didn't found any, do you get the name for hebcal api?

**Comment by rt400** [comment]
Sorry, but the sensor works differently than what you are looking for.
The name sensor only changes if there is a holiday approaching that week.
For example, if there are 2 holidays in a week (like Passover) then on Sunday you will see the name of the first holiday and after the holiday is over you will see the name of the next holiday, in the case of the example, the seventh of Passover
I am closing this ISSUE.
