### ISSUE TITLE
Hebrew/English

### ISSUE THREAD

**Issue by Kerosenb** [rt400/Jewish-Sabbaths-Holidays#5]
Hi I’ve just installed this on my HA. Seems to work well, but the sensors are returning in Hebrew. Is there any way to get English values?

**Comment by rt400** [comment]
in the next release.. still working on it

**Comment by Kerosenb** [comment]
thanks

Kerrin Rosenberg
T.    +44 (0)20 3170 5924
M.  +44 (0)7917 365040
E.    ***@***.******@***.***>
W.  cardano.com<https://www.cardano.com/>

6 Bevis Marks, London, EC3A 7BA

Assistant: Justine Wilson | T. +44 (0)20 3170 5913 | E. ***@***.***

**Comment by rt400** [comment]
@Kerosenb i just add new version with english language.. plz update it and let me know how its works.

**Comment by Kerosenb** [comment]
Thanks Yuval

I just updated and restarted HA, but still Hebrew

Maybe I need to adjust a config file somewhere – my HA is set to English as default language

Kerrin Rosenberg
T.    +44 (0)20 3170 5924
M.  +44 (0)7917 365040
E.    ***@***.******@***.***>
W.  cardano.com<https://www.cardano.com/>

6 Bevis Marks, London, EC3A 7BA

Assistant: Justine Wilson | T. +44 (0)20 3170 5913 | E. ***@***.***

**Comment by rt400** [comment]
yes, you need to add in sensor config : 
`language: english`

**Comment by Kerosenb** [comment]
Perfect, thanks

Yes, this works well

Thanks for picking this up so quickly

B’vracha

Kerrin Rosenberg
T.    +44 (0)20 3170 5924
M.  +44 (0)7917 365040
E.    ***@***.******@***.***>
W.  cardano.com<https://www.cardano.com/>

6 Bevis Marks, London, EC3A 7BA

Assistant: Justine Wilson | T. +44 (0)20 3170 5913 | E. ***@***.***
