### ISSUE TITLE
שגיאה בפרטי שבת (17.7.21)

### ISSUE THREAD

**Issue by tzagim** [rt400/Jewish-Sabbaths-Holidays#6]
אני מניח שניתן לפנות אליך בעברית.
זה מה שמתקבל לגבי השבת הקרובה:
"פרשת דְּבָרִים , שַׁבָּת חֲזוֹן , שַׁבָּת חֲזוֹן , שַׁבָּת חֲזוֹן , שַׁבָּת חֲזוֹן , שַׁבָּת חֲזוֹן , שַׁבָּת חֲזוֹן , שַׁבָּת חֲזוֹן , שַׁבָּת חֲזוֹן , שַׁבָּת חֲזוֹן , שַׁבָּת חֲזוֹן , שַׁבָּת חֲזוֹן , שַׁבָּת חֲזוֹן , שַׁבָּת חֲזוֹן , שַׁבָּת חֲזוֹן"

**Comment by rt400** [comment]
הקדמת אותי...העלתי עדכון
