### ISSUE TITLE
Some sensors are pulling info - others are not

### ISSUE THREAD

**Issue by menocode** [rt400/Jewish-Sabbaths-Holidays#7]
Hi 

Some of the sensors work - other's don't. I have the configuration files set up in Configuration.yaml and the Latitude and longitude are NOT set up ip the configuration.Yaml. TheyL&L and TimeZone are set up properly in the General Tab from my original install. For some reason - it's not being picked up correctly. 
  
The following code is showing up in the Hebcal_data_full.json
```  "location": {
        "city": "32°11′N 35°0′E Asia/Jerusalem",
        "latitude": 32.19961974235943,
        "longitude": 35.011625289917,
        "title": "32°11′N 35°0′E Asia/Jerusalem",
        "tzid": "Asia/Jerusalem"
```

Daf Yomi - Shows up fine
Mincha  - Invalid timestamp 
Candle Lighting - Invalid timestamp

**Comment by rt400** [comment]
can you share your sensor configuration ?
also did you setup the latitude and longitude and timezone on HA ?

**Comment by menocode** [comment]
Hi 

I believe this is my mistake. The Sensors from your hack like shabbat times are working. The Sensors like "Jewish Calendar Upcoming Candle Lighting" which I believe are pulled from the sensor 

```jewish_calendar``` 

in my Configuration.yaml have problems. Some work and some do not. 

Your sensors, e.g. פרשת השבוע and כניסת השבת are working

**Comment by rt400** [comment]
yes. this jewish_calendar are different from my sensor. glad to know that my sensor are work 😎
