### ISSUE TITLE
הוספת "zmanim"

### ISSUE THREAD

**Issue by tzagim** [rt400/Jewish-Sabbaths-Holidays#8]
היי,
תודה על עבודתך אני משתמש בזה הרבה.
יש אפשרות להוסיף גם את "zmanim" מתוך hebcal?
לצורך מידע על תחילת וסיום צומות

תודה על הכל

**Comment by tzagim** [comment]
היי,
תודה על עבודתך אני משתמש בזה הרבה.
יש אפשרות להוסיף גם את "zmanim" מתוך hebcal?
לצורך מידע על תחילת וסיום צומות

תודה על הכל

**Comment by rt400** [comment]
Check for update (read the readme first for add Zmanim) and you will get sensor called : sensor.hebcal_zmanim that have an attributes with the Zamain for the current day(today). have fun...
