### ISSUE TITLE
Differances from Jewish Calendar Integration

### ISSUE THREAD

**Issue by TKpizza** [rt400/Jewish-Sabbaths-Holidays#9]
I currently use the [Jewish calendar integration](https://www.home-assistant.io/integrations/jewish_calendar), how is this different? if there are any pros i would love to switch.

**Comment by TKpizza** [comment]
Never mind i saw the closed comment and read through the read me a i little more carefully and got my answer.

**Comment by rt400** [comment]
Hi, I would like to know what is your choose ? and what the really the different that you find..

**Comment by TKpizza** [comment]
im liking it a lot so far.

Can you add a erev shabbos and erev yomtov sensor?
also can there be an option to break up the zemanim sensor attributes to be their own sensors?
